# Generated by Django 5.2.6 on 2025-10-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontent",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("index_welcome_title", "Главная - заголовок"),
                    ("index_welcome_text", "Главная - описание"),
                    ("index_service_romantic", "Главная - романтический ужин"),
                    ("index_service_banquets", "Главная - банкеты"),
                    ("index_service_delivery", "Главная - доставка"),
                    ("index_contacts_address", "Главная - адрес"),
                    ("index_contacts_phone", "Главная - телефон"),
                    ("index_contacts_email", "Главная - email"),
                    ("index_contacts_hours", "Главная - режим работы"),
                    ("about_history_title", "О нас - заголовок истории"),
                    ("about_history_content", "О нас - история"),
                    ("about_mission_title", "О нас - заголовок миссии"),
                    ("about_mission_content", "О нас - миссия"),
                    ("about_team_chef", "О нас - шеф-повар"),
                    ("about_team_manager", "О нас - менеджер"),
                    ("about_team_sommelier", "О нас - сомелье"),
                    ("contacts_address", "Контакты - адрес"),
                    ("contacts_phone", "Контакты - телефон"),
                    ("contacts_email", "Контакты - email"),
                    ("contacts_hours", "Контакты - часы работы"),
                    ("contacts_services_romantic", "Контакты - романтический ужин"),
                    ("contacts_services_corporate", "Контакты - корпоративное"),
                    ("contacts_atmosphere", "Контакты - атмосфера"),
                    ("contacts_cuisine", "Контакты - авторская кухня"),
                    ("contacts_chef", "Контакты - шеф-повар"),
                    ("contacts_service", "Контакты - премиальное обслуживание"),
                    ("contacts_welcome", "Контакты - приветствие"),
                    ("footer_copyright", "Футер - копирайт"),
                    ("footer_tagline", "Футер - слоган"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Тип контента",
            ),
        ),
    ]
