# Generated by Django 5.2.6 on 2025-10-08 18:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField(help_text="Дата бронирования")),
                (
                    "time_slot",
                    models.TimeField(
                        choices=[
                            (datetime.time(12, 0), "12:00 - 14:00"),
                            (datetime.time(14, 0), "14:00 - 16:00"),
                            (datetime.time(16, 0), "16:00 - 18:00"),
                            (datetime.time(18, 0), "18:00 - 20:00"),
                            (datetime.time(20, 0), "20:00 - 22:00"),
                            (datetime.time(22, 0), "22:00 - 00:00"),
                        ],
                        help_text="Временной слот бронирования",
                    ),
                ),
                (
                    "guests_count",
                    models.PositiveSmallIntegerField(help_text="Количество гостей"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Подтверждено"),
                            ("pending", "В ожидании"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        help_text="Статус бронирования",
                        max_length=20,
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True, help_text="Особые пожелания", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "table",
                    models.ForeignKey(
                        help_text="Забронированный столик",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-created_at"],
            },
        ),
    ]
